const {JSDOM}=require('jsdom');const fs=require('fs');const assert=require('node:assert/strict');
const root=require('node:path').resolve(__dirname,'..');const wait=()=>new Promise(r=>setTimeout(r,25));
async function boot(role='gate',url='https://only.test/admin.html?tab=tickets&event=event&eventView=gate'){
 const dom=new JSDOM(fs.readFileSync(root+'/admin.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''),{url,runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,d=w.document,calls=[],errors=[];w.addEventListener('error',e=>errors.push(e.message));w.HTMLCanvasElement.prototype.getContext=()=>({});w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLMediaElement.prototype.pause=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};w.confirm=()=>false;
 let ticket={id:'ticket',event_id:'event',event_name:'Only Meeting',ticket_code:'TEST-001',driver_name:'Pessoa Teste',vehicle_plate:'ABC1D23',status:'active',ticket_kind:'expo',qr_token:'test-token-at-least-16-characters'};
 const activity=[];
 w.OnlySupabase={getUser:async()=>({id:'gate-user',email:'test@example.test'}),rest:async(url,opts)=>{calls.push(url);if(url.startsWith('profiles?'))return [{role,display_name:'Portaria'}];if(url==='rpc/admin_event_gate_events')return [{id:'event',name:'Only Meeting',starts_at:'2026-10-23T23:00:00Z'}];if(url==='rpc/admin_event_gate_summary_for_event')return {active_tickets:1,inside_event:ticket.status==='checked_in'?1:0,recent_activity:activity};if(url==='rpc/admin_search_event_tickets')return [{...ticket}];if(url==='rpc/admin_inspect_event_ticket')return {...ticket};if(url==='rpc/admin_checkin_event_ticket'){if(ticket.status==='checked_in')throw Error('Entrada já registrada');ticket={...ticket,status:'checked_in',last_entry_at:new Date().toISOString()};activity.push({...ticket,action:'entry',action_label:'Entrada confirmada',created_at:ticket.last_entry_at});return {...ticket};}if(url==='rpc/admin_undo_event_entry'){assert.equal(opts.body.p_expected_entry_at,ticket.last_entry_at);assert(opts.body.p_reason.length>=3);ticket={...ticket,status:'active',last_entry_at:null};return {...ticket};}if(role==='admin')return [];throw Error('Forbidden unexpected call '+url);}};
 for(const f of ['admin.js','admin-event-tools.js'])w.eval(fs.readFileSync(root+'/assets/js/'+f,'utf8'));
 await wait();return {w,d,calls,errors,dom,setTicket:patch=>{ticket={...ticket,...patch}}};
}
(async()=>{
 let {w,d,calls,errors,setTicket}=await boot();
 assert(d.body.classList.contains('admin-gate-only'));assert.equal(d.querySelectorAll('[data-admin-tab]').length,1);assert(!d.querySelector('[data-admin-event-gate]').hidden,'F5 must restore event automatically');
 const search=async()=>{d.querySelector('[data-scanner-input]').value='Pessoa';d.querySelector('[data-scanner-search]').click();await wait();};
 await search();d.querySelector('[data-ticket-action="entry"]').click();d.querySelector('[data-ticket-action="entry"]').click();await wait();
 assert.equal(calls.filter(x=>x==='rpc/admin_checkin_event_ticket').length,1,'double-click single request');assert(d.querySelector('.admin-gate-success').textContent.includes('Entrada confirmada'));assert(d.querySelector('[data-ticket-activity]').textContent.includes('TEST-001'));assert(d.querySelector('[data-ticket-action="entry"]').disabled);
 d.querySelector('[data-ticket-action="exit"]').click();await wait();assert.equal(calls.filter(x=>x==='rpc/admin_checkin_event_ticket').length,1,'exit cancelled');
 d.querySelector('[data-ticket-action="undo"]').click();await wait();assert(d.querySelector('dialog').open);d.querySelector('[data-cancel-undo]').click();await wait();assert.equal(calls.filter(x=>x==='rpc/admin_undo_event_entry').length,0);
 d.querySelector('[data-ticket-action="undo"]').click();await wait();d.querySelector('dialog textarea').value='Validei o veículo errado';d.querySelector('dialog form').dispatchEvent(new w.Event('submit',{cancelable:true}));await wait();assert(d.querySelector('.admin-gate-success').textContent.includes('Entrada desfeita'));assert(!d.querySelector('[data-ticket-action="entry"]').disabled);
 d.querySelector('[data-next-ticket]').click();await wait();assert(!d.querySelector('[data-ticket-action]'));assert(d.querySelector('[data-ticket-result]').textContent.includes('próximo ingresso'));
 await search();setTicket({status:'checked_in',last_entry_at:'2026-09-30T18:00:00Z'});w.dispatchEvent(new w.Event('focus'));await wait();assert(d.querySelector('[data-ticket-action="entry"]').disabled,'another operator update must refresh current ticket');
 assert.deepEqual(errors,[]);assert(calls.every(x=>x.startsWith('profiles?')||['rpc/admin_inspect_event_ticket','rpc/admin_event_gate_events','rpc/admin_event_gate_summary_for_event','rpc/admin_search_event_tickets','rpc/admin_checkin_event_ticket','rpc/admin_undo_event_entry'].includes(x)));w.close();
 const admin=await boot('admin','https://only.test/admin.html?tab=tickets&event=event&eventView=management');assert(!admin.d.querySelector('[data-event-view="management"]').hidden,'admin F5 restores subview');assert(new URL(admin.w.location).searchParams.get('event')==='event');assert.deepEqual(admin.errors,[]);admin.w.close();
 console.log('PASS: gate/admin refresh restoration, single-flight check-in, success/next, history, exit confirmation, undo cancellation/confirmation, gate isolation');
})().catch(e=>{console.error(e);process.exit(1)});
